# travis ci config file
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

# command to install module
install:
  - pip install -e .

# command to run tests
script:
  - python -m unittest tests/*.py
